language: php

php:
    - 7.2
    - 7.3
    - 7.4
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
    - if [[ $TRAVIS_PHP_VERSION = hhv* ]]; then echo hhvm.php7.all=1 >> /etc/hhvm/php.ini; fi

install:
    - composer self-update
    - composer install

script:
    - vendor/bin/phpunit --colors --coverage-text --verbose
